services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6969:80"
    restart: unless-stopped
    container_name: companero
    # Healthcheck is defined in the Dockerfile
