name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build-and-smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: course-companion:test

      - name: Run container
        run: |
          docker run -d --rm -p 8080:80 --name cc course-companion:test
          echo "Waiting for container..." && sleep 3
          curl -fS http://localhost:8080/index.html | head -n 5

      - name: Stop container
        if: always()
        run: docker stop cc || true
